# fly.toml app configuration file generated for vgmify on 2023-05-18T11:06:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "vgmify"
app = "vgmify"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
